### ISSUE TITLE
Move dam logic from spring run to winter run

### ISSUE THREAD

**Issue by liz-fw** [Reorienting-to-Recovery/winterRunDSM#5]
incorporate below/above dam logic from springRunDSM `wip` to winterRunDSM

**Comment by ErinCain** [comment]
Recommend tracking back to commits/PR merges that maddee did for spring run update:
(spring one one -https://github.com/Reorienting-to-Recovery/springRunDSM/pull/3) (https://github.com/Reorienting-to-Recovery/DSMtemperature/pull/4)
- create above dam spawn and rear proportions in DSMhabitat (looks like spawn and rear proportions are already in there) 
- create above dam degree days in DSMtemperature (if this feels complicated, just use spring ones) 
- add above dam logic into model script (and see if it is in any other scripts) (check spawn success)
